export const BOOK_CREATE_REQUEST = "BOOK_CREATE_REQUEST";
export const BOOK_CREATE_SUCCESS = "BOOK_CREATE_SUCCESS";
export const BOOK_CREATE_FAIL = "BOOK_CREATE_FAIL";
export const BOOK_CREATE_RESET = "BOOK_CREATE_RESET";

export const BOOK_DETAILS_REQUEST = "BOOK_DETAILS_REQUEST";
export const BOOK_DETAILS_SUCCESS = "BOOK_DETAILS_SUCCESS";
export const BOOK_DETAILS_FAIL = "BOOK_DETAILS_FAIL";
export const BOOK_DETAILS_RESET = "BOOK_DETAILS_FAIL";
export const BOOK_PAY_REQUEST = "BOOK_PAY_REQUEST";
export const BOOK_PAY_SUCCESS = "BOOK_PAY_SUCCESS";
export const BOOK_PAY_FAIL = "BOOK_PAY_FAIL";
export const BOOK_PAY_RESET = "BOOK_PAY_RESET";

export const BOOK_LIST_MY_REQUEST = "BOOK_LIST_MY_REQUEST";
export const BOOK_LIST_MY_SUCCESS = "BOOK_LIST_MY_SUCCESS";
export const BOOK_LIST_MY_FAIL = "BOOK_LIST_MY_FAIL";
export const BOOK_LIST_MY_RESET = "BOOK_LIST_MY_RESET";

export const BOOK_LIST_REQUEST = "BOOK_LIST_REQUEST";
export const BOOK_LIST_SUCCESS = "BOOK_LIST_SUCCESS";
export const BOOK_LIST_FAIL = "BOOK_LIST_FAIL";

export const BOOK_DELIVER_REQUEST = "BOOK_DELIVER_REQUEST";
export const BOOK_DELIVER_SUCCESS = "BOOK_DELIVER_SUCCESS";
export const BOOK_DELIVER_FAIL = "BOOK_DELIVER_FAIL";
export const BOOK_DELIVER_RESET = "BOOK_DELIVER_RESET";

export const BOOK_UPDATE_REQUEST = "BOOK_UPDATE_REQUEST";
export const BOOK_UPDATE_SUCCESS = "BOOK_UPDATE_SUCCESS";
export const BOOK_UPDATE_FAIL = "BOOK_UPDATE_FAIL";
export const BOOK_UPDATE_RESET = "BOOK_UPDATE_RESET";
