export const PATIENT_LIST_REQUEST = "PATIENT_LIST_REQUEST";
export const PATIENT_LIST_SUCCESS = "PATIENT_LIST_SUCCESS";
export const PATIENT_LIST_ERROR = "PATIENT_LIST_ERROR";

export const PATIENT_ADD_REQUEST = "PATIENT_ADD_REQUEST";
export const PATIENT_ADD_SUCCESS = "PATIENT_ADD_SUCCESS";
export const PATIENT_ADD_ERROR = "PATIENT_ADD_ERROR";

export const PATIENT_DETAILS_REQUEST = "PATIENT_DETAILS_REQUEST";
export const PATIENT_DETAILS_SUCCESS = "PATIENT_DETAILS_SUCCESS";
export const PATIENT_DETAILS_ERROR = "PATIENT_DETAILS_ERROR";

export const PATIENT_UPDATE_REQUEST = "PATIENT_UPDATE_REQUEST";
export const PATIENT_UPDATE_SUCCESS = "PATIENT_UPDATE_SUCCESS";
export const PATIENT_UPDATE_ERROR = "PATIENT_UPDATE_ERROR";
export const PATIENT_UPDATE_RESET = "PATIENT_UPDATE_RESET";

export const PATIENT_DELETE_REQUEST = "PATIENT_DELETE_REQUEST";
export const PATIENT_DELETE_SUCCESS = "PATIENT_DELETE_SUCCESS";
export const PATIENT_DELETE_ERROR = "PATIENT_DELETE_ERROR";
export const PATIENT_DELETE_RESET = "PATIENT_DELETE_RESET";

export const PATIENT_ROOM_NO_REQUEST = "PATIENT_ROOM_NO_REQUEST";
export const PATIENT_ROOM_NO_SUCCESS = "PATIENT_ROOM_NO_SUCCESS";
export const PATIENT_ROOM_NO_ERROR = "PATIENT_ROOM_NO_ERROR";
export const PATIENT_ROOM_NO_RESET = "PATIENT_ROOM_NO_RESET";
